### ISSUE TITLE
Docker Cloud isn't building

### ISSUE THREAD

**Issue by adamradocz** [BOINC/boinc-client-docker#39]
The Docker Cloud isn't build and every container build status is failed.

**Comment by marius311** [comment]
@davidpanderson just needs to add himself as source provider again (see my emails from yesterday). Sorry about the disruptions due to my tinkering.

**Comment by marius311** [comment]
Alternatively, I learned yesterday in my tinkering that the hooks we're using to build the images are actually secretly available on Hub as well, just not documented. Does that mean we can use Hub? I forget if that had a better way to link the source provider or not...

**Comment by marius311** [comment]
> the hooks we're using to build the images are actually secretly available on Hub as well, just not documented

I should say, I've read this, although I've not tested it yet.

**Comment by marius311** [comment]
Ok, I've now tested and indeed it hooks work on the Hub as well. I was able to link this source and build, although it crashed I think due to a problem in the script. But at least its clear it ran. https://hub.docker.com/r/boinc/client_test/builds/b3yjxtbtov62huoxauf2qf/

I'll leave it up to you if you want to move over to Hub. 

In the meantime though, @davidpanderson, could you please relink the Cloud account? Thanks.

**Comment by adamradocz** [comment]
@marius311 I don't have too much experience in any of them, so won't vote on this.

**Comment by adamradocz** [comment]
What's the pros and cons of them? Hub can update the images when the main image is updated.

**Comment by marius311** [comment]
Pro's of Cloud are that at some point probably Hub is retired, also to me its seems there's less wait time in the build wait queue. A con though is that the source linking is all screwed hence we're still waiting on David. I might be wrong but I don't see where "Hub can update the images when the main image is updated." There's "Repository links" but that's only for other repos, not other tags within the same repo. In any case that's a bit a moot point since Hub does (secretly) have build hooks so we can do whatever.

**Comment by davidpanderson** [comment]
I didn't see an email yesterday.  In any case, I went to the docker site
and got as far finding this document page:
https://docs.docker.com/docker-cloud/builds/link-source/
but couldn't find the "Cloud settings" link referred to there.

**Comment by adamradocz** [comment]
@davidpanderson Can you try the steps detailed in the issue #6

**Comment by davidpanderson** [comment]
Those directions don't work any more.
In step 2, when I go to that URL I don't see Source Providers -> Github

**Comment by adamradocz** [comment]
@marius311 Do you have any idea?

**Comment by marius311** [comment]
@davidpanderson the URL is now https://cloud.docker.com/swarm/boinc/settings or alternatively go to the top right and click on your username, select the BOINC organizatoin, then go to organization settings

**Comment by adamradocz** [comment]
Ubuntu and Intel driver were updated so the containers should have been updated. Can we do something to connect the GitHub and the Docker in any way?

**Comment by marius311** [comment]
Yea I am really impressed / surprised at the number of pulls. I'd be curious to know more about how this is actually being used, not sure exactly how best to connect with these people. 

@davidpanderson can you follow the updated instructions above and relink the repo? Just message me if something doesn't work.

**Comment by davidpanderson** [comment]
I think I linked the repo.  Marius, please check; if any problem I'll find you in Campbell tomorrow.

**Comment by adamradocz** [comment]
It's working, thanks!
